In [4]:
import numpy as np

# **Generating Data**

Zero, Ones & Identity Matrix 

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [12]:
10*np.ones((3,4))

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

np.random.random()

In [13]:
np.random.random((2,3))

array([[0.82248888, 0.99453481, 0.27020265],
       [0.15971934, 0.34824658, 0.35767989]])

np.random.randn()

In [14]:
np.random.randn(2,3) 

array([[-1.7013884 , -0.68156155, -1.80928255],
       [-0.96797005,  0.35496264, -0.30202895]])

In [21]:
R=np.random.randn(100)
print(R)
print(R.mean())
print(np.mean(R))
print(R.var())
print(R.std())

[-2.45710103  0.15650838 -1.70738337 -0.44734338  1.43118007  0.088137
  0.81003376 -0.09716104  0.85736024 -1.87197941 -0.42362604 -2.45017292
 -0.75126744 -1.50572429  1.58527972 -0.79224452  0.62926264 -1.11893625
  1.50280363 -0.94204075  1.56176713 -0.80585793 -0.19352165  0.39833512
 -0.94832402  0.26409766 -0.70092436  0.80311713  0.42033328 -0.45145501
  0.4301921   1.21658161  0.9639855  -0.81776808 -0.08166556 -1.10008367
  0.02093324 -0.10853847  0.79114208 -1.87426386  0.4986157  -0.78255886
 -0.82970043 -0.39550591  0.94153522 -0.20132023 -1.09214597 -0.38486305
  0.70267041  0.5540941   0.59815904 -0.51891854 -0.25487867 -0.98652384
 -0.19832311  1.42226542 -1.59787596 -0.07595337 -0.62373889  0.6289346
  1.97155891 -0.25685396  0.5670726   0.0896231  -0.40655468  0.33054075
 -0.72370136  0.85346421 -0.21950038 -0.95511334  0.21491869  0.80592363
 -0.06672178  1.4066288   0.96033851 -2.26368476  0.91693374  0.62038267
 -0.14651368 -0.83531677 -0.91906314  0.40199388  2.30

In [26]:
R = np.random.randn(1000,3)
print(R)
print(R.mean(axis=0))
print(R.mean(axis=1))

[[-1.19699834 -2.03494372  1.37267275]
 [ 0.73480352 -0.04921845  0.10436312]
 [ 0.07768226 -0.55613794 -0.53410678]
 ...
 [-0.32746955 -0.08095609 -0.55474951]
 [ 0.59704442 -0.69738242  1.61228421]
 [ 0.45888563  0.18336314 -1.78694004]]
[-0.00476821  0.02555828  0.06863402]
[-6.19756437e-01  2.63316064e-01 -3.37520818e-01  8.76333727e-01
  3.05845943e-01 -9.38640746e-02  5.68920714e-01  7.94329648e-01
  1.05636109e-01 -9.23151825e-01 -7.66325718e-02  8.56596264e-01
 -2.52781792e-01 -1.33842893e-01  8.27402137e-01  1.06722713e+00
 -6.28919415e-01 -5.52111350e-01  6.86169224e-01  1.07629514e+00
  5.10439555e-01 -9.40316226e-01  1.22654220e-01  9.14156435e-01
  3.16423287e-01 -3.69343494e-01  1.52468064e-02  4.03965388e-01
 -4.77979370e-01  5.60452750e-01 -5.38159408e-01  9.09098388e-01
  4.34903173e-01 -1.41532587e+00  5.06160957e-02 -4.52090074e-02
  1.04760548e+00 -2.92692867e-02  3.11086627e-01  5.91135951e-01
 -8.44785323e-01  2.64611776e-01  4.77764443e-01  7.08656144e-02
 -1.433

np.random.randint(low, high = None, size=None, dtype='1')

In [22]:
np.random.randint(0,10,size=(3,3))

array([[9, 7, 4],
       [1, 7, 9],
       [2, 4, 1]])

np.random.choice(a, size=None, replace= True, p = None)



- Generates random sample from a given 1-D array
- If an ndarray is given, a random sample is generated from its elements.
- If an integer is integer is given, the random sample is generated as if 'a' were np.arange(a)

In [28]:
np.random.choice(5,size=(4,4))

array([[4, 4, 1, 3],
       [2, 3, 4, 2],
       [1, 4, 1, 2],
       [3, 3, 1, 3]])

np.linspace
- return **x** evenly spaced samples calculated over a specified interval [start,stop]

In [31]:
np.linspace(2.0,11.0,num=5)

array([ 2.  ,  4.25,  6.5 ,  8.75, 11.  ])