### Accessing Elements 
#### Difference between Lists and array

In [ ]:
import numpy as np

Lists

In [ ]:
L = [[1,2],[3,4]]
print(L)

[[1, 2], [3, 4]]


In [ ]:
L[0][1]

2

Array

In [ ]:
A= np.array([[1,2],[3,4]])

In [ ]:
print(A)

[[1 2]
 [3 4]]


In [ ]:
A[0][1]

2

In [ ]:
A[0,1]

2

In [ ]:
A[:,0]

array([1, 1])

### Transposing, exponentially raising each element

In [ ]:
A.T # Transpose

array([[1, 3],
       [2, 4]])

In [ ]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

### Dot Product, Determinants

In [ ]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [ ]:
B = np.array([[1,2,3],[4,5,6]])

In [ ]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [ ]:
A.dot(B.T)

ValueError: ignored

In [ ]:
np.linalg.det(A)

-2.0000000000000004

In [ ]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [ ]:
np.diag(A)

array([1, 4])

### Changing Shape of Arrays

In [ ]:
a1 =np.array([[1,2],[3,4]])
a1

array([[1, 2],
       [3, 4]])

In [ ]:
a1.resize(1,4)
a1

array([[1, 2, 3, 4]])

In [ ]:
a1.reshape(2,2)

array([[1, 2],
       [3, 4]])

### Appending & Deleting array elements

In [ ]:
A = np.array([1,2,3,4])
A

array([1, 2, 3, 4])

In [ ]:
np.append(A,[9,10])

array([ 1,  2,  3,  4,  9, 10])

In [ ]:
np.insert(A,1,5)

array([1, 5, 2, 3, 4])

Deleting

In [ ]:

#Working on 1D 
arr = np.arange(5) 
print("arr : \n", arr) 
print("Shape : ", arr.shape) 
  
# deletion from 1D array  
  
object = 2
a = np.delete(arr, object) 
print("\ndeleteing {} from array : \n {}".format(object,a)) 
print("Shape : ", a.shape) 
  
object = [1, 2] 
b = np.delete(arr, object) 
print("\ndeleteing {} from array : \n {}".format(object,b)) 
print("Shape : ", b.shape) 

arr : 
 [0 1 2 3 4]
Shape :  (5,)

deleteing 2 from array : 
 [0 1 3 4]
Shape :  (4,)

deleteing [1, 2] from array : 
 [0 3 4]
Shape :  (3,)
